// This snippet file was generated by processing the source file:
// ./storage-next/upload-files.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_upload_blob_modular]
import { initializeApp } from "firebase/app";

import { getStorage, ref, uploadBytes, getDownloadURL } from "firebase/storage";

const firebaseConfig = {
    apiKey: "AIzaSyCGgSq2r4sLPUEsJ5_wFOHXDIoWd2bL17E",
    authDomain: "ilusion-gt.firebaseapp.com",
    projectId: "ilusion-gt",
    storageBucket: "ilusion-gt.appspot.com",
    messagingSenderId: "65020428920",
    appId: "1:65020428920:web:59876fabe8cdfdebe6e38d",
    measurementId: "G-GCQDMWS0CD"

};

const app = initializeApp(firebaseConfig);




const storage = getStorage(app);

export function uploadFile(file: File) {
    return new Promise((resolve, reject) => {

        const storageRef = ref(storage, file.name);

        uploadBytes(storageRef, file).then(() => {
            getDownloadURL(storageRef).then(url =>{
                console.log(url)
                resolve(url)
            })
        });
    })
}
// [END storage_upload_blob_modular]